package form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import DAO.nhanvienDAO;
import helper.DialogHP;
import helper.ShareHP;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author niqua
 */
public class DoiMatKhauDialog extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhauDialog
     */
    public DoiMatKhauDialog() {
        
        initComponents();
        init();
                
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_maNV = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        lbl_matKhau = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JPasswordField();
        lbl_matKhauMoi2 = new javax.swing.JLabel();
        txt_matKhauMoi2 = new javax.swing.JPasswordField();
        lbl_matKhauMoi = new javax.swing.JLabel();
        txt_matKhauMoi = new javax.swing.JPasswordField();
        btn_dongY = new javax.swing.JButton();
        btn_huyBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ĐỔI MẬT KHẨU");

        lbl_maNV.setText("Tên đăng nhâp");

        lbl_matKhau.setText("Mật khẩu");

        lbl_matKhauMoi2.setText("Nhập lại mật khẩu");

        txt_matKhauMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauMoi2ActionPerformed(evt);
            }
        });

        lbl_matKhauMoi.setText("Mật khẩu mới");

        txt_matKhauMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauMoiActionPerformed(evt);
            }
        });

        btn_dongY.setText("Đồng ý");
        btn_dongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dongYActionPerformed(evt);
            }
        });

        btn_huyBo.setText("Hủy bỏ");
        btn_huyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(lbl_maNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_maNV, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(lbl_matKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matKhauMoi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btn_dongY)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_matKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_matKhau)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_matKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btn_huyBo)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_maNV)
                    .addComponent(lbl_matKhau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_matKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_matKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_matKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_matKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dongY)
                    .addComponent(btn_huyBo))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_matKhauMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauMoi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauMoi2ActionPerformed

    private void txt_matKhauMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauMoiActionPerformed

    private void btn_dongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dongYActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_btn_dongYActionPerformed

    private void btn_huyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyBoActionPerformed
        huyBo();
    }//GEN-LAST:event_btn_huyBoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhauDialog().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dongY;
    private javax.swing.JButton btn_huyBo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_matKhau;
    private javax.swing.JLabel lbl_matKhauMoi;
    private javax.swing.JLabel lbl_matKhauMoi2;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JPasswordField txt_matKhauMoi;
    private javax.swing.JPasswordField txt_matKhauMoi2;
    // End of variables declaration//GEN-END:variables

    private void init(){
        setLocationRelativeTo(null);
        txt_maNV.setText(ShareHP.USER.getTenNV());
        txt_maNV.setEditable(false);
    }
    
    nhanvienDAO dao = new nhanvienDAO();
    
    private void doiMatKhau(){
        
        String matKhau = new String(txt_matKhau.getPassword());
        String matKhauMoi = new String(txt_matKhauMoi.getPassword());
        String matKhauMoi2 = new String(txt_matKhauMoi2.getPassword());
        
        if (!matKhau.equalsIgnoreCase(ShareHP.USER.getMatkhau())) {
            DialogHP.alert(this, "Sai mật khẩu!");
        }else if(txt_matKhauMoi.getText().isBlank()){
            DialogHP.alert(this, "Không được để trống mật khẩu");
        }else if (!matKhauMoi.equalsIgnoreCase(matKhauMoi2)) {
            DialogHP.alert(this, "Xác nhận mật khẩu không đúng!");
        }else{
              try {
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLBANHANG;integratedSecurity=true");
            PreparedStatement ps = conn.prepareStatement("UPDATE NHANVIEN SET MATKHAU=?  WHERE HOTEN = ?");
            ps.setString(1, txt_matKhauMoi.getText());
            ps.setString(2, txt_maNV.getText());

            ps.executeUpdate();
            ps.close();
            conn.close();
           

        } catch (Exception e) {
            e.printStackTrace();
        } 
            DialogHP.alert(this, "Đổi mật khẩu thành công!");
        }
    }
    
    private void huyBo(){
        if (DialogHP.confirm(this, "Bạn có thực sự muốn thoát không!")) {
            this.dispose();
        }
    } 
    
}
