/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import CLASS.Sanpham_1;
import CLASS.hdthanhtoan;
import CLASS.sanpham;
import CLASS.hdthanhtoanct;
import DAO.LoaiSanphamDAO;
import DAO.SanphamDao;
import DAO.hoadonthanhtoanDAO;
import static java.lang.System.exit;
import java.text.SimpleDateFormat;
import java.util.Date;
import form.dangnhap;
import helper.DateHP;
import helper.DialogHP;
import helper.JDBCHP;
import java.awt.Checkbox;
import java.awt.HeadlessException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diepd
 */
public class hoadonthanhtoan extends JInternalFrame {

    DAO.hoadonthanhtoanDAO daott = new hoadonthanhtoanDAO();
    dangnhap dn = new dangnhap();
    String spp = "";
    Date date = new Date();// Return thời gian hiện tại với định dạng rất khó coi
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // Định dạng lại date  
    String dburl = "jdbc:sqlserver://localhost:1433;databasename=QLBANHANG;integratedSecurity=true";

    DefaultTableModel model = new DefaultTableModel() {
        public Class<?> getColumnClass(int column) {
            switch (column) {
                case 0:
                    return String.class;
                case 1:
                    return String.class;
                case 2:
                    return String.class;

                case 3:
                    return String.class;
                case 4:
                    return Boolean.class;
                default:
                    return String.class;
            }
        }
    };
    ArrayList<sanpham> splist = new ArrayList<>();

    /**
     * Creates new form hoadonthanhtoan
     */
    public hoadonthanhtoan() {
        initComponents();
        innit();

    }

    void innit() {
        testloadTable();
//        setLocationRelativeTo(null);
        String a = helper.ShareHP.USER.getTenNV();
        txtnguoitao.setText(a);
        ngaytao.setText(sdf.format(date));  // Hiển thị ra text field
        txtnguoitao.setEditable(false);
        btnthanhtoan.setEnabled(false);
        btnnhaptien.setEnabled(false);
        txtma.setEditable(false);
        txttongtien.setEditable(false);
        addClum();
        tiendua.setVisible(false);
        tralai.setVisible(false);
        fillcbkhach();
        fillcbosp();
        filltbsp();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablexem = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnguoitao = new javax.swing.JTextField();
        ngaytao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnthemkhach = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txttimkhach = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtsdtkhach = new javax.swing.JTextField();
        idkhach = new javax.swing.JTextField();
        cbkhachhang = new javax.swing.JComboBox<>();
        btnthemmoisanpham = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsanpham = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txttimsanpham = new javax.swing.JTextField();
        bntthemsp = new javax.swing.JButton();
        btncapnhap = new javax.swing.JButton();
        txttongtien = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblthemsanpham = new javax.swing.JTable();
        btnnhaptien = new javax.swing.JButton();
        tiendua = new javax.swing.JLabel();
        tralai = new javax.swing.JLabel();
        jtiennhap = new javax.swing.JLabel();
        jtienthua = new javax.swing.JLabel();
        cbsanpham = new javax.swing.JComboBox<>();
        btnmoi = new javax.swing.JButton();
        btnthanhtoan = new javax.swing.JButton();
        bntthoat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhoadon = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblsanphamchitiet = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Ngày tạo:");

        jLabel6.setText("Người tạo");

        ngaytao.setBackground(new java.awt.Color(0, 0, 0));
        ngaytao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ngaytao.setText("ngay");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addComponent(txtnguoitao, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngaytao)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnguoitao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ngaytao))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách Hàng"));

        btnthemkhach.setText("tìm");
        btnthemkhach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnthemkhachMouseClicked(evt);
            }
        });
        btnthemkhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemkhachActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên khách hàng");

        jLabel5.setText("Chọn khách hàng");

        jLabel9.setText("ID KHÁCH");

        jLabel7.setText("Số điện thoại");

        txtsdtkhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtkhachActionPerformed(evt);
            }
        });

        cbkhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHỌN KHÁCH HÀNG" }));
        cbkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkhachhangActionPerformed(evt);
            }
        });

        btnthemmoisanpham.setText("THÊM KHÁCH MỚI");
        btnthemmoisanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoisanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txttimkhach)
                    .addComponent(cbkhachhang, 0, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnthemkhach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtsdtkhach, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnthemmoisanpham)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idkhach, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttimkhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthemkhach)
                    .addComponent(jLabel7)
                    .addComponent(txtsdtkhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthemmoisanpham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(idkhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SẢN PHẨM"));

        tblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblsanpham);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("TỔNG TIỀN:");

        jLabel1.setText("Tìm sản phẩm");

        bntthemsp.setText("thêm");
        bntthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntthemspActionPerformed(evt);
            }
        });

        btncapnhap.setText("CẬP NHẬP");
        btncapnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhapActionPerformed(evt);
            }
        });

        txttongtien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblthemsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TÊN SẢN PHẨM"
            }
        ));
        tblthemsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthemsanphamMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblthemsanpham);

        btnnhaptien.setText("NHẬP TIỀN");
        btnnhaptien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhaptienActionPerformed(evt);
            }
        });

        tiendua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tiendua.setText("Tiền Khách Đưa:");

        tralai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tralai.setText("Trả Lại:");

        jtiennhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtiennhap.setForeground(new java.awt.Color(0, 0, 255));

        jtienthua.setForeground(new java.awt.Color(255, 0, 51));

        cbsanpham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        cbsanpham.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsanphamItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btncapnhap)
                    .addComponent(cbsanpham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnnhaptien)
                                .addGap(18, 18, 18)
                                .addComponent(tiendua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtiennhap, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tralai)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtienthua)
                                .addGap(52, 52, 52)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttimsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntthemsp)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntthemsp)
                    .addComponent(txttimsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btncapnhap)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttongtien)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnnhaptien)
                                    .addComponent(tiendua)
                                    .addComponent(tralai)
                                    .addComponent(jtienthua)
                                    .addComponent(jtiennhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnmoi.setText("Làm Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnthanhtoan.setText("LƯU HOÁ ĐƠN");
        btnthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoanActionPerformed(evt);
            }
        });

        bntthoat.setText("Thoat");
        bntthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnthanhtoan)
                        .addGap(38, 38, 38)
                        .addComponent(bntthoat)
                        .addGap(36, 36, 36))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmoi)
                    .addComponent(btnthanhtoan)
                    .addComponent(bntthoat))
                .addContainerGap())
        );

        tablexem.addTab("TẠO HOÁ ĐƠN", jPanel4);

        tblhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Hoá đơn", "Nhân viên tạo", "Khách hàng", "Ngày Tạo", "Tổng tiền"
            }
        ));
        tblhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblhoadon);

        jLabel8.setText("DANH SÁCH HOÁ ĐƠN");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("CHI TIẾT HOÁ ĐƠN"));

        jLabel11.setText("MÃ HOÁ ĐƠN");

        txtma.setForeground(new java.awt.Color(0, 51, 204));

        tblsanphamchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SẢN PHẨM", "TÊN SẢN PHẨM", "SỐ LƯỢNG"
            }
        ));
        jScrollPane3.setViewportView(tblsanphamchitiet);

        jLabel12.setText("SẢN PHẨM TRONG HOÁ ĐƠN");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 147, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablexem.addTab("DANH SÁCH", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(tablexem, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablexem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntthoatActionPerformed
        this.dispose();
        new mainform().setVisible(true);
    }//GEN-LAST:event_bntthoatActionPerformed

    private void btnthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoanActionPerformed
        if (txttimkhach.getText().isBlank()) {
            helper.DialogHP.alert(this, "phải thêm khách vào  đơn không được để trống");
        } else if (txttongtien.getText().isBlank()) {
            System.out.println("LỖI THANH TOÁN");
        } else {
            insert();
            clear();
            tiendua.setVisible(false);
            tralai.setVisible(false);
            jtiennhap.setText("");
            jtienthua.setText("");

        }
    }//GEN-LAST:event_btnthanhtoanActionPerformed
    void insert() {
        CLASS.hdthanhtoan model = getModel();
        model.setNgaytao(new Date());
        try {
            daott.insert(model);
            try {
                Connection conn = DriverManager.getConnection(dburl);
                String sql = "select * from HOADONTT where IDNHANVIEN = ? and IDKHACHHANG = ? and TONGTIEN = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, String.valueOf(helper.ShareHP.USER.getIdnhanvien()));
                ps.setString(2, idkhach.getText());
                ps.setString(3, txttongtien.getText());
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    int a = rs.getInt("IDHOADONTT");
                    for (int i = 0; i < tblsanpham.getRowCount(); i++) {
                        CLASS.hdthanhtoanct hdtt = new hdthanhtoanct();
                        int b = (int) Double.parseDouble(tblsanpham.getValueAt(i, 3).toString());
                        hdtt.setIdhoadontt(a);
                        hdtt.setIdsanpham((int) tblsanpham.getValueAt(i, 0));
                        hdtt.setSoluong(b);
                        daott.insertHDCT(hdtt);
                        CLASS.sanpham sp = new sanpham();
                        sp.setA(b);
                        sp.setMaSP((int) tblsanpham.getValueAt(i, 0));
                        daott.updatesp(sp);
                    }
                }
            } catch (Exception e) {
                DialogHP.alert(this, "lỗi thanh toán thử lại");
            }

            testloadTable();
            helper.DialogHP.alert(this, "Thêm mới thành công!");
        } catch (HeadlessException e) {
            helper.DialogHP.alert(this, "Thêm mới thất bại!");
        }

    }
    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        clear();
        tiendua.setVisible(false);
        tralai.setVisible(false);
        txttongtien.setText("");
        jtiennhap.setText("");
        jtienthua.setText("");
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btncapnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhapActionPerformed
        try {
            update();
            tinhgia();
            tongtien();
            txttongtien.setText(String.valueOf(tongtien()));
            btnnhaptien.setEnabled(true);
            tiendua.setVisible(false);
            tralai.setVisible(false);
            jtiennhap.setText("");
            jtienthua.setText("");

        } catch (Exception e) {
            helper.DialogHP.alert(this, "lỗi");
        }

    }//GEN-LAST:event_btncapnhapActionPerformed

    private void bntthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntthemspActionPerformed
        spp = txttimsanpham.getText();
        for (sanpham sp : splist(spp)) {
            addtable();
        }
        tiendua.setVisible(false);
        tralai.setVisible(false);
        btnnhaptien.setEnabled(true);
    }//GEN-LAST:event_bntthemspActionPerformed

    private void cbkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkhachhangActionPerformed
        addinforkhach();
        cbkhachhang.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_cbkhachhangActionPerformed

    private void txtsdtkhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtkhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtkhachActionPerformed

    private void btnthemkhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemkhachActionPerformed
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM KHACHHANG where TENKH= ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, txttimkhach.getText());

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                DialogHP.alert(this, "đã thêm khách ");
                ad();

            } else {
                DialogHP.alert(this, "không tìm thấy!");

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnthemkhachActionPerformed

    private void btnthemkhachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnthemkhachMouseClicked

    }//GEN-LAST:event_btnthemkhachMouseClicked
    int index = -1;
    private void tblhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonMouseClicked
        this.index = tblhoadon.getSelectedRow();
        if (this.index >= 0) {
            this.testloadtbsp();

        }

    }//GEN-LAST:event_tblhoadonMouseClicked

    private void btnthemmoisanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoisanphamActionPerformed

        form.mainform mf = new mainform();
        mf.setVisible(true);
        form.khachhangform kh = new khachhangform();
        kh.setVisible(true);

    }//GEN-LAST:event_btnthemmoisanphamActionPerformed

    private void tblthemsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthemsanphamMouseClicked
        if (evt.getClickCount() == 1) {
            this.index = tblthemsanpham.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                spp = (String) tblthemsanpham.getValueAt(this.index, 0);
                for (sanpham sp : splist(spp)) {
                    addtable();
                }
            }
        }
        tiendua.setVisible(false);
        tralai.setVisible(false);
        jtiennhap.setText("");
        jtienthua.setText("");
        btnnhaptien.setEnabled(false);
        btnthanhtoan.setEnabled(false);// TODO add your handling code here

    }//GEN-LAST:event_tblthemsanphamMouseClicked

    private void btnnhaptienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhaptienActionPerformed
        try {
            String sc = JOptionPane.showInputDialog("Nhập số tiền khách trả");
            String s = txttongtien.getText();
            if (Double.parseDouble(sc) < Double.parseDouble(s)) {
                DialogHP.alert(this, "tiền nhập phải lớn hơn tổng tiền");
            } else {
                double b = Double.parseDouble(sc) - Double.parseDouble(s);
                jtiennhap.setText(sc);
                jtienthua.setText(String.valueOf(b));
                tiendua.setVisible(true);
                tralai.setVisible(true);
                btnthanhtoan.setEnabled(true);
            }

        } catch (Exception e) {
            DialogHP.alert(this, "Lỗi");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnnhaptienActionPerformed

    private void cbsanphamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsanphamItemStateChanged
 DefaultTableModel model = (DefaultTableModel) tblthemsanpham.getModel();
        model.setRowCount(0);
        try {
            if (cbsanpham.getSelectedItem().equals("Tất cả")) {
                filltbsp();
            } else {
                List<Sanpham_1> list = SanphamDao.findbang(cbsanpham.getSelectedItem().toString());
                for (Sanpham_1 nv : list) {
                    Object[] row = {
                        nv.getTensp()};
                    model.addRow(row);
                }
            }
        } catch (Exception e) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbsanphamItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadonthanhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadonthanhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadonthanhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadonthanhtoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoadonthanhtoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntthemsp;
    private javax.swing.JButton bntthoat;
    private javax.swing.JButton btncapnhap;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnnhaptien;
    private javax.swing.JButton btnthanhtoan;
    private javax.swing.JButton btnthemkhach;
    private javax.swing.JButton btnthemmoisanpham;
    private javax.swing.JComboBox<String> cbkhachhang;
    private javax.swing.JComboBox<String> cbsanpham;
    private javax.swing.JTextField idkhach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jtiennhap;
    private javax.swing.JLabel jtienthua;
    private javax.swing.JLabel ngaytao;
    private javax.swing.JTabbedPane tablexem;
    private javax.swing.JTable tblhoadon;
    private javax.swing.JTable tblsanpham;
    private javax.swing.JTable tblsanphamchitiet;
    private javax.swing.JTable tblthemsanpham;
    private javax.swing.JLabel tiendua;
    private javax.swing.JLabel tralai;
    private javax.swing.JTextField txtma;
    private javax.swing.JTextField txtnguoitao;
    private javax.swing.JTextField txtsdtkhach;
    private javax.swing.JTextField txttimkhach;
    private javax.swing.JTextField txttimsanpham;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
 void loadlisst() {

    }

    void clear() { // xoa trang cac du lieu
        txttimkhach.setText("");
        txtsdtkhach.setText("");
        txttimsanpham.setText("");
        idkhach.setText("");
        DefaultTableModel model = (DefaultTableModel) tblsanpham.getModel();
        model.setRowCount(0);
    }

    public void fillcbosp() {
        try {
            String dburl = "jdbc:sqlserver://localhost:1433;databaseName=QLBANHANG;integratedSecurity=true";
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM LoaiSP";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.cbsanpham.addItem(rs.getString("TENLOAISP"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void ad() {// add thong tin khi an tim kiem khach hang
        try {

            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM KHACHHANG WHERE TENKH=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, txttimkhach.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.txtsdtkhach.setText(rs.getString("SDT"));
                this.idkhach.setText(rs.getString("IDKHACHHANG"));
            }
        } catch (Exception e) {
        }
    }

    void tinhgia() {// thanh tien cho san pham

        for (int i = 0; i < model.getRowCount(); i++) {
            int a = 0;
            int b = (int) Double.parseDouble(tblsanpham.getValueAt(i, 3).toString());
            int c = (int) Double.parseDouble(tblsanpham.getValueAt(i, 2).toString());
            a = b * c;
            tblsanpham.setValueAt(a, i, 5);
        }
    }

    void update() { // ham check de xoa san pham trong bang san pham
        for (int i = 0; i < model.getRowCount(); i++) {
            Boolean isDelete = (Boolean) tblsanpham.getValueAt(i, 4);
            if (isDelete == true) {
                model.removeRow(i);
                i = -1;
            }
        }

    }

    public double tongtien() { // tinh tong tien
        int sum = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            sum = (int) (sum + Double.parseDouble(tblsanpham.getValueAt(i, 5).toString()));
        }
        return sum;
    }

    public void fillcbkhach() { // do giu lieu len combo khach 
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM KHACHHANG";
            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.cbkhachhang.addItem(rs.getString("TENKH"));
            }

        } catch (Exception e) {
        }
    }

    void aa() {
        DefaultTableModel tbl = (DefaultTableModel) tblsanpham.getModel();
        tblsanpham.getColumn(3).setResizable(resizable);
        for (int i = 0; i < tblsanpham.getRowCount(); i++) {
            tblsanpham.setColumnSelectionAllowed(isSelected);
        }
    }

    public void addClum() {
        model.addColumn("ID sản phẩm");
        model.addColumn("Tên sản phẩm");
        model.addColumn("Giá");
        model.addColumn("Số lượng");
        model.addColumn("Xóa");
        model.addColumn("Thành tiền");
        tblsanpham.setModel(model);
    }

    public void addtable() { // add san pham vao table 

        splist.forEach((sp) -> {

            model.addRow(new Object[]{sp.getMaSP(), sp.getTensp(), sp.getGiaban(), 1, false, ""});
        });

    }

    public ArrayList<CLASS.sanpham> splist(String name) {
        splist.removeAll(splist);
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM SANPHAM where TENSP = N'" + name + "'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            sanpham sp;
            while (rs.next()) {
                sp = new sanpham(rs.getInt("IDSANPHAM"), rs.getString("TENSP"), rs.getFloat("GIABAN"));
                splist.add(sp);
            }
        } catch (Exception e) {
        }
        return splist;
    }

    public void filltbsp() { // do giu lieu len combobox san pham
        DefaultTableModel model = (DefaultTableModel) tblthemsanpham.getModel();
        model.setRowCount(0);
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM SANPHAM";
            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
//                this.cbsanpham.addItem(rs.getString("TENSP"));
                model.addRow(new Object[]{rs.getString(2)});
            }

        } catch (Exception e) {
        }

    }

    public void addinforkhach() { // them thong tin khach
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM KHACHHANG WHERE TENKH=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, (String) this.cbkhachhang.getSelectedItem());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.txttimkhach.setText(cbkhachhang.getSelectedItem().toString());
                this.txtsdtkhach.setText(rs.getString("SDT"));
                this.idkhach.setText(rs.getString("IDKHACHHANG"));

            }
        } catch (Exception e) {
        }
    }

    void testloadTable() {
        DefaultTableModel model = (DefaultTableModel) tblhoadon.getModel();
        model.setRowCount(0);
        String sql = "select hoadontt.IDHOADONTT,nhanvien.HOTEN,KHACHHANG.TENKH,hoadontt.NGAYTAOHD, HOADONTT.TONGTIEN\n"
                + "from HOADONTT join nhanvien on nhanvien.IDNHANVIEN = HOADONtt.IDNHANVIEN\n"
                + "				join KHACHHANG on KHACHHANG.IDKHACHHANG = HOADONTT.IDKHACHHANG\n"
                + "				join hoadonttct on hoadonttct.IDHOADONTT = hoadontt.IDHOADONTT\n"
                + "				group by hoadontt.IDHOADONTT,nhanvien.HOTEN,KHACHHANG.TENKH,hoadontt.NGAYTAOHD, HOADONTT.TONGTIEN";

        try {
            ResultSet rs = null;

            try {
                rs = JDBCHP.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getDate(4), rs.getDouble(5)});
                }
                System.out.println("xong");
            } finally {
                rs.getStatement().getConnection().close();
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    void testloadtbsp() {
        DefaultTableModel model = (DefaultTableModel) tblsanphamchitiet.getModel();
        model.setRowCount(0);
        String a = tblhoadon.getValueAt(index, 0).toString();
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "select HOADONTTCT.IDSANPHAM,SANPHAM.TENSP,HOADONTTCT.SOLUONG from HOADONTTCT join SANPHAM on SANPHAM.IDSANPHAM= HOADONTTCT.IDSANPHAM\n"
                    + "where  IDHOADONTT =?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, a);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                txtma.setText(a);
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getInt(3)});

            }
        } catch (Exception e) {
        }
    }

    CLASS.hdthanhtoan getModel() {
        CLASS.hdthanhtoan model = new hdthanhtoan();
        model.setNgaytao(helper.DateHP.toDate(ngaytao.getText()));
        model.setIDkhach(Integer.parseInt(idkhach.getText()));
        model.setIDNHANVIEN(helper.ShareHP.USER.getIdnhanvien());
        model.setTONGTIEN((float) Double.parseDouble(txttongtien.getText()));
        return model;
    }

}
