/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import CLASS.hoadonnhapct;
import CLASS.sanpham;
import DAO.hoadonnhapDAO;
import helper.JDBCHP;
import helper.DateHP;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class hoadonnhap extends JInternalFrame {

    DAO.hoadonnhapDAO hdn = new hoadonnhapDAO();
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<sanpham> splist = new ArrayList();
    Date date = new Date();// Return thời gian hiện tại với định dạng rất khó coi
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // Định dạng lại date 
    String dburl = "jdbc:sqlserver://localhost:1433;databasename=QLBANHANG;integratedSecurity=true";
    int index = -1;

    /**
     * Creates new form hoadonnhap
     */
    public hoadonnhap() {
        initComponents();
        txtnhanvien.setText(helper.ShareHP.USER.getTenNV());
        txtngaytao.setText(sdf.format(date));
        txtngaytao.setEditable(false);
        fillcbsp();
        txttongtien.setEditable(false);
        loadtblhoadon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhoadonnhap = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblhdnct = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnhanvien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtngaytao = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cbsanpham = new javax.swing.JComboBox<>();
        bntthemmoisp = new javax.swing.JButton();
        txtsoluong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnthemsp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsanpham = new javax.swing.JTable();
        txttongtien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblhoadonnhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ HOÁ ĐƠN", "NGƯỜI tạo", "NGÀY TẠO", "TỔNG TIỀN"
            }
        ));
        tblhoadonnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhoadonnhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblhoadonnhap);

        tblhdnct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mã hoá đơn", "id sản phẩm", "TÊN SP", "số lượng", "GIA NHAP", "thành tiền"
            }
        ));
        jScrollPane3.setViewportView(tblhdnct);

        jLabel7.setText("HOÁ ĐƠN CHI TIẾT");

        jLabel3.setText("DANH SÁCH HOÁ ĐƠN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DANH SÁCH", jPanel2);

        jButton4.setText("THOÁT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("TÊN NHÂN VIÊN");

        jLabel1.setText("NGÀY TẠO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN HOÁ ĐƠN"));

        cbsanpham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHỌN SẢN PHẨM" }));
        cbsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsanphamActionPerformed(evt);
            }
        });

        bntthemmoisp.setText("Thêm sản phẩm mới");
        bntthemmoisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntthemmoispActionPerformed(evt);
            }
        });

        jLabel4.setText("SỐ LƯỢNG");

        btnthemsp.setText("Thêm Vào DS");
        btnthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemspActionPerformed(evt);
            }
        });

        jButton2.setText("Xoá sản phẩm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN SP", "GIÁ NHẬP", "SỐ LƯỢNG", "THÀNH TIỀN"
            }
        ));
        jScrollPane1.setViewportView(tblsanpham);

        txttongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttongtienActionPerformed(evt);
            }
        });

        jLabel6.setText("TỔNG TIỀN:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnthemsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cbsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntthemmoisp)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntthemmoisp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthemsp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton3.setText("LƯU HOÁ ĐƠN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TẠO HOÁ ĐƠN", jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("HOÁ ĐƠN NHẬP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed

        try {
            String tensp = (String) cbsanpham.getSelectedItem();
            if (txtsoluong.getText().isBlank()) {
                helper.DialogHP.alert(this, "số lượng không được để trống");
                return;
            }
            int soluong;
            try {
                soluong = Integer.valueOf(txtsoluong.getText());
                if (soluong < 0) {
                    helper.DialogHP.alert(this, "Số lượng phải lớn hơn 0");
                    return;
                }

            } catch (Exception e) {
                helper.DialogHP.alert(this, "Phải nhập kiểu số");
                return;
            }
            for (sanpham sp : splist(tensp)) {
                addtable();
            }
            tongtien();
            txttongtien.setText(String.valueOf(tongtien()));
            txtsoluong.setText("");
            cbsanpham.setSelectedIndex(0);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnthemspActionPerformed
    public void addtable() { // add san pham vao table 
        DefaultTableModel model = (DefaultTableModel) tblsanpham.getModel();
        splist.forEach((sp) -> {
            double a = sp.getGiaban();
            System.out.println(a);
            double b = Double.parseDouble(txtsoluong.getText());
            double c = a * b;
            model.addRow(new Object[]{sp.getMaSP(), sp.getTensp(), sp.getGiaban(), b, c});
        });

//        txttongtien.setText(String.valueOf(tongtien()));
    }

    public double tongtien() { // tinh tong tien
        double sum = 0;
        System.out.println("cccc");
        for (int i = 0; i < tblsanpham.getRowCount(); i++) {
            System.out.println("a");
            double a = Double.parseDouble(tblsanpham.getValueAt(i, 4).toString());
            System.out.println(a);
//            sum =  (sum + Double.parseDouble( tblsanpham.getValueAt(i, 4).toString()));
            sum = a + sum;

        }
        return sum;
    }

    public ArrayList<CLASS.sanpham> splist(String name) {
        splist.removeAll(splist);
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM SANPHAM where TENSP = N'" + name + "'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            sanpham sp;
            while (rs.next()) {
                sp = new sanpham(rs.getInt("IDSANPHAM"), rs.getString("TENSP"), rs.getFloat("GIANHAP"));
                splist.add(sp);
            }
        } catch (Exception e) {
        }
        return splist;
    }
    private void txttongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttongtienActionPerformed

    private void cbsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsanphamActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.index = tblsanpham.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblsanpham.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            if (this.index == i) {
                model.removeRow(i);
//                i = -1;
                break;
            }
        }
        tongtien();
        txttongtien.setText(String.valueOf(tongtien()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        insert();
    }//GEN-LAST:event_jButton3ActionPerformed
    void insert() {
        CLASS.hoadonnhap model = getModel();
        model.setNgaytao(new Date());
        try {
            hdn.insert(model);
            try {
                Connection conn = DriverManager.getConnection(dburl);
                String sql = "select * from HOADONNHAP where IDNHANVIEN = ?  and TONGTIEN = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, String.valueOf(helper.ShareHP.USER.getIdnhanvien()));
                ps.setString(2, txttongtien.getText());
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    int a = rs.getInt("IDHOADONNHAP");
                    System.out.println(a);
                    for (int i = 0; i < tblsanpham.getRowCount(); i++) {
                        CLASS.hoadonnhapct hdtt = new hoadonnhapct();
                        int b = (int) Double.parseDouble(tblsanpham.getValueAt(i, 3).toString());
                        hdtt.setIdhoadonnhap(a);
                        hdtt.setIdsanpham((int) tblsanpham.getValueAt(i, 0));
                        hdtt.setSoluong(b);
                        hdn.insertct(hdtt);
                        CLASS.sanpham sp = new sanpham();
                        sp.setA(b);
                        sp.setMaSP((int) tblsanpham.getValueAt(i, 0));
                        hdn.updatesp(sp);
                    }
                }
            } catch (Exception e) {
            }
            helper.DialogHP.alert(this, "LƯU THÀNH CÔNG");
            loadtblhoadon();

        } catch (Exception e) {
            helper.DialogHP.alert(this, "LỖI! ");
        }
    }

    private void tblhoadonnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhoadonnhapMouseClicked
        this.index = tblhoadonnhap.getSelectedRow();
        if (this.index >= 0) {
            this.loadhdnct();

        }
    }//GEN-LAST:event_tblhoadonnhapMouseClicked

    private void bntthemmoispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntthemmoispActionPerformed
         mainform mf = new  mainform();
         mf.setVisible(true);
        QLSanphamJFrame sp = new QLSanphamJFrame();
        sp.setVisible(true);
        
    }//GEN-LAST:event_bntthemmoispActionPerformed
    public void fillcbsp() { // do giu lieu len combobox san pham
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "SELECT * FROM SANPHAM";
            PreparedStatement ps = conn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.cbsanpham.addItem(rs.getString("TENSP"));
            }
        } catch (Exception e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadonnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadonnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadonnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadonnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoadonnhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntthemmoisp;
    private javax.swing.JButton btnthemsp;
    private javax.swing.JComboBox<String> cbsanpham;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblhdnct;
    private javax.swing.JTable tblhoadonnhap;
    private javax.swing.JTable tblsanpham;
    private javax.swing.JTextField txtngaytao;
    private javax.swing.JTextField txtnhanvien;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
void loadtblhoadon() {
        DefaultTableModel model = (DefaultTableModel) tblhoadonnhap.getModel();
        model.setRowCount(0);
        String sql = "select HOADONNHAP.IDHOADONNHAP ,NHANVIEN.HOTEN,HOADONNHAP.NGAYTAO,HOADONNHAP.TONGTIEN \n"
                + "         from HOADONNHAP join NHANVIEN on NHANVIEN.IDNHANVIEN=HOADONNHAP.IDNHANVIEN\n"
                + "		 group by HOADONNHAP.IDHOADONNHAP ,NHANVIEN.HOTEN,HOADONNHAP.NGAYTAO,HOADONNHAP.TONGTIEN";
        try {
            ResultSet rs = null;

            try {
                rs = JDBCHP.executeQuery(sql);
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getDate(3), rs.getDouble(4)});
                }
            } finally {
                rs.getStatement().getConnection().close();
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    void loadhdnct() {
        DefaultTableModel model = (DefaultTableModel) tblhdnct.getModel();
        model.setRowCount(0);
        String a = tblhoadonnhap.getValueAt(index, 0).toString();
        try {
            Connection conn = DriverManager.getConnection(dburl);
            String sql = "select HOADONNHAPCT.IDHOADONNHAP,SANPHAM.IDSANPHAM,SANPHAM.TENSP,HOADONNHAPCT.SOLUONG,SANPHAM.GIANHAP,(SANPHAM.GIANHAP* HOADONNHAPCT.SOLUONG) as tong1\n"
                    + "   from HOADONNHAPCT join SANPHAM on SANPHAM.IDSANPHAM = HOADONNHAPCT.IDSANPHAM where IDHOADONNHAP= ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, a);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getString(3), rs.getDouble(4), rs.getDouble(5), rs.getDouble(6)});
            }
        } catch (Exception e) {
        }
    }

    CLASS.hoadonnhap getModel() {
        CLASS.hoadonnhap model = new CLASS.hoadonnhap();
        model.setNgaytao(helper.DateHP.toDate(txtngaytao.getText()));
        model.setIdnhanvien(helper.ShareHP.USER.getIdnhanvien());
        model.setTongtien((float) Double.parseDouble(txttongtien.getText()));
        return model;
    }
}
